datavolume:
  container_name: nginx-data
  image: debian:latest
  restart: on-failure:10
  volumes:
    - /opt/nginx/certs:/etc/nginx/certs
    - /opt/nginx/htpasswd:/etc/nginx/htpasswd
    - /opt/nginx/vhosts:/etc/nginx/vhost.d
    - /opt/nginx/html:/usr/share/nginx/html

nginx-proxy:
  container_name: nginx-proxy
  image: jwilder/nginx-proxy
  restart: on-failure:10
  ports:
    - 80:80
    - 443:443
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  volumes_from:
    - datavolume

letsencrypt:
  container_name: letsencrypt
  image: jrcs/letsencrypt-nginx-proxy-companion
  restart: on-failure:10
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
  volumes_from:
    - nginx-proxy
