services:

  nginx:
    image: nginxproxy/nginx-proxy:1.9
    restart: always
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    environment:
      - ENABLE_IPV6=true
      - SSL_POLICY=Mozilla-Custom
    volumes:
      - certs:/etc/nginx/certs
      - vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /repos/docker-nginx-proxy/vhost.d:/etc/nginx/vhost.d:ro
      - /repos/docker-nginx-proxy/files/body_size.conf:/etc/nginx/conf.d/body_size.conf:ro
      - /repos/docker-nginx-proxy/files/nginx.tmpl:/app/nginx.tmpl
    networks:
      - frontend
    ports:
      - 80:80
      - 443:443
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  letsencrypt:
    image: nginxproxy/acme-companion:2.6
    restart: always
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    networks:
      - frontend
    environment:
      - NGINX_PROXY_CONTAINER=proxy-nginx-1
    depends_on:
      - nginx

volumes:
  certs:
  vhost.d:
  html:
  acme:

networks:
  frontend:
